name: ds_gallery
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animations: ^2.0.3
  cupertino_icons: ^1.0.5
  device_frame: ^1.1.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.1
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  intl: ^0.17.0
  provider: ^6.0.3
  component_library:
    git:
      url: https://github.com/may-andro/component_library.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/images/
    - assets/logo/
    - lib/data/component/foundation/color/config/
    - lib/data/component/foundation/typography/config/
    - lib/data/component/atom/button/config/fab/
    - lib/data/component/atom/button/config/filled_button/
    - lib/data/component/atom/button/config/ghost_button/
    - lib/data/component/atom/button/config/icon_button/
    - lib/data/component/atom/button/config/outlined_button/
  uses-material-design: true

flutter_gen:
  output: lib/assets/
